version: '3.9'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - api
  qr-web:
      build: .
      env_file:
          .env
      ports:
        - '80:80'
      depends_on:
        - mongo
      networks:
      - api
networks:
  api:
    driver: bridge